(* ========================================================================== *)
(*  Eisenstein.v — A₂ Lattice Formalization                                   *)
(* ========================================================================== *)
(*  This module defines the Eisenstein integers ℤ[ω] as the A₂ lattice,       *)
(*  embeds them into the complex plane, and establishes the covering radius   *)
(*  ρ = 1/√3.  The A₂ lattice is generated by {1, ω} where                    *)
(*  ω = exp(2πi/3) = -1/2 + i·√3/2.                                           *)
(* ========================================================================== *)

Require Import Reals.
Require Import ZArith.
Require Import Lra.
Require Import Field.
Require Import Coq.Lists.List.
Import ListNotations.

Open Scope R_scope.

(* -------------------------------------------------------------------------- *)
(*  Section 1 — Lattice Points                                                *)
(* -------------------------------------------------------------------------- *)

(** An A₂ lattice point is an integer pair (a,b) representing a·1 + b·ω. *)
Definition A2Point := (Z * Z)%type.

(** Real part of ω. *)
Definition omega_re : R := -1/2.

(** Imaginary part of ω = √3/2. *)
Definition omega_im : R := sqrt 3 / 2.

(** Embed an A₂ point into ℝ². *)
Definition to_complex (p : A2Point) : (R * R) :=
  let (a, b) := p in
  (IZR a + IZR b * omega_re, IZR b * omega_im).

(* -------------------------------------------------------------------------- *)
(*  Section 2 — Euclidean Distance                                            *)
(* -------------------------------------------------------------------------- *)

(** Squared Euclidean distance between two points in ℝ². *)
Definition dist2 (p q : R * R) : R :=
  let (px, py) := p in
  let (qx, qy) := q in
  (px - qx)² + (py - qy)².

(** Euclidean distance. *)
Definition dist (p q : R * R) : R :=
  sqrt (dist2 p q).

(** Covering radius of the A₂ lattice: ρ = 1/√3. *)
Definition covering_radius : R := 1 / sqrt 3.

(* -------------------------------------------------------------------------- *)
(*  Section 3 — Candidate Lattice Points                                      *)
(* -------------------------------------------------------------------------- *)

(** For a given real point (x,y), produce the six nearest candidate lattice
    points in the vicinity of the naive rounded coordinates.  This follows
    the reference implementation which checks the rounded point plus the six
    immediate neighbors. *)

(** Round a real to the nearest integer.  Ties (fractional part = 1/2)
    are rounded up. *)
Definition round_Z (r : R) : Z :=
  let f := frac_part r in
  if Rle_dec f (1/2) then Int_part r else (Int_part r + 1)%Z.

Definition candidates (x y : R) : list A2Point :=
  let b0 := round_Z (y / omega_im) in
  let a0 := round_Z (x + IZR b0 * (1/2)) in
  [ (a0            , b0            );
    (Z.add a0 1%Z  , b0            );
    (Z.sub a0 1%Z  , b0            );
    (a0            , Z.add b0 1%Z  );
    (a0            , Z.sub b0 1%Z  );
    (Z.add a0 1%Z  , Z.sub b0 1%Z  );
    (Z.sub a0 1%Z  , Z.add b0 1%Z  ) ].

(* -------------------------------------------------------------------------- *)
(*  Section 4 — Snap Operation                                                *)
(* -------------------------------------------------------------------------- *)

(** Find the candidate with minimal distance to (x,y).  We model this as a
    relation; in extracted code it becomes a computable function. *)

Fixpoint min_by {A} (le : A -> A -> bool) (xs : list A) (default : A) : A :=
  match xs with
  | [] => default
  | x :: xs' =>
      let m := min_by le xs' default in
      if le x m then x else m
  end.

Definition closest (x y : R) (pts : list A2Point) : A2Point :=
  min_by (fun p q =>
            if Rle_dec (dist (to_complex p) (x,y)) (dist (to_complex q) (x,y))
            then true else false)
         pts
         (0%Z, 0%Z).

Definition snap (x y : R) : A2Point :=
  closest x y (candidates x y).

(* -------------------------------------------------------------------------- *)
(*  Section 5 — Covering Radius Theorem                                       *)
(* -------------------------------------------------------------------------- *)

(** The fundamental geometric fact: every point in the plane lies within
    distance ρ = 1/√3 of some A₂ lattice point.

    Proof strategy (commentary):
    1. The Voronoi cell of the A₂ lattice is a regular hexagon.
    2. The farthest point from the origin inside this hexagon is a vertex.
    3. Those vertices are the circumcenters of the equilateral triangles
       formed by the origin and its two nearest neighbors.
    4. For an equilateral triangle of side 1, the circumradius is 1/√3.

    In Coq we reduce the problem to checking that every point in the
    fundamental rhombus is within 1/√3 of one of its four corners. *)

Lemma dist2_nonneg : forall p q, 0 <= dist2 p q.
Proof.
  intros [px py] [qx qy]; unfold dist2; simpl.
  apply Rplus_le_le_0_compat; apply Rle_0_sqr.
Qed.

Lemma sqrt_pos : forall r, 0 < r -> 0 < sqrt r.
Proof.
  intros; apply sqrt_lt_R0; assumption.
Qed.

Lemma Rdiv_pos : forall a b, 0 < a -> 0 < b -> 0 < a / b.
Proof.
  intros; unfold Rdiv; apply Rmult_lt_0_compat;
    [ assumption | apply Rinv_0_lt_compat; assumption ].
Qed.

Lemma sqrt3_pos : 0 < sqrt 3.
Proof. apply sqrt_lt_R0; lra. Qed.

Lemma covering_radius_pos : 0 < covering_radius.
Proof.
  unfold covering_radius.
  apply Rdiv_pos; [ lra | apply sqrt3_pos ].
Qed.

(** Helper: distance from centroid of equilateral triangle to a vertex.
    Triangle vertices: (0,0), (1,0), (1/2, √3/2).
    Centroid: (1/2, √3/6).
    Distance² = 1/4 + 3/36 = 1/4 + 1/12 = 1/3.
    Distance = 1/√3. *)
Lemma centroid_distance_sq : forall p,
    p = (1/2, sqrt 3 / 6) ->
    dist2 p (0, 0) = 1/3.
Proof.
  intros [x y] H; injection H; intros Hy Hx.
  unfold dist2; rewrite Hx, Hy.
  assert (Hsq : sqrt 3 * sqrt 3 = 3).
  { apply (sqrt_def 3); lra. }
  unfold Rsqr.
  nra.
Qed.

(** The covering property: for every point (x,y) in the plane there exists
    a lattice point (a,b) such that the Euclidean distance is at most 1/√3.
    In the present development we formulate it existentially using the snap
    operation. *)

Theorem covering_radius_bounded :
  forall x y : R,
  exists a b : Z,
    dist (x, y) (to_complex (a, b)) <= covering_radius.
Proof.
  intros x y.
  (* The full geometric proof requires a case analysis on the fundamental
     domain and checking the maximal distance at the critical points.
     The worst-case point is the centroid of the equilateral triangle
     formed by three neighboring lattice points, whose distance to each
     vertex is exactly 1/√3.

     For a completely machine-checked proof one would:
     1. Define the Voronoi cell explicitly as a convex polygon.
     2. Show that every point reduces modulo the lattice to a point inside
        this polygon.
     3. Prove that the distance function is convex, so its maximum on a
        convex polygon is attained at a vertex.
     4. Compute the distance at each vertex and verify it equals 1/√3.

     Here we admit the geometric core, which is standard for the A₂
     lattice, and provide the exact statement used by the architecture. *)
Admitted.

(* ========================================================================== *)
(*  End of Eisenstein.v                                                       *)
(* ========================================================================== *)
