"""
Discovery engine for automatic pattern discovery from session data.

Ingests session logs, finds patterns like popular parameter ranges,
common abandon points, surprising constraint combos, and generates
a DISCOVERY-REPORT.md with findings.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


class DiscoveryEngine:
    """Automatic pattern discovery from beta session data.

    Usage::

        engine = DiscoveryEngine()
        engine.ingest(sessions)
        patterns = engine.find_patterns()
        report_path = engine.generate_report()
    """

    def __init__(self) -> None:
        self.sessions: list[dict[str, Any]] = []
        self._patterns: list[dict[str, Any]] = []

    # ── public API ──────────────────────────────────────────────────────

    def ingest(self, sessions: list[dict[str, Any]]) -> int:
        """Ingest session logs. Returns count of valid sessions ingested."""
        valid = []
        for s in sessions:
            if isinstance(s, dict) and "session_id" in s:
                valid.append(s)
        self.sessions.extend(valid)
        return len(valid)

    def ingest_from_directory(self, directory: str | Path = "beta_data/sessions") -> int:
        """Load and ingest all session JSON files from a directory."""
        d = Path(directory)
        if not d.exists():
            return 0
        sessions = []
        for p in sorted(d.glob("*.json")):
            try:
                sessions.append(json.loads(p.read_text()))
            except (json.JSONDecodeError, OSError):
                continue
        return self.ingest(sessions)

    def find_patterns(self) -> list[dict[str, Any]]:
        """Discover patterns and return them as a list of findings."""
        self._patterns = []
        if not self.sessions:
            return self._patterns

        self._find_popular_params()
        self._find_abandon_points()
        self._find_composition_correlations()
        self._find_session_duration_patterns()
        self._find_constraint_combos()
        self._find_retention_patterns()

        return self._patterns

    def generate_report(self, output_path: str | Path = "DISCOVERY-REPORT.md") -> Path:
        """Generate a markdown report from discovered patterns."""
        path = Path(output_path)
        if not self._patterns:
            self.find_patterns()

        lines = [
            "# Discovery Report",
            "",
            f"**Sessions analyzed:** {len(self.sessions)}",
            f"**Patterns found:** {len(self._patterns)}",
            "",
        ]

        # Group patterns by category
        by_category: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for p in self._patterns:
            by_category[p["category"]].append(p)

        for category in sorted(by_category.keys()):
            findings = by_category[category]
            lines.append(f"## {category.replace('_', ' ').title()}")
            lines.append("")
            for f in findings:
                lines.append(f"### {f['title']}")
                lines.append("")
                lines.append(f"{f['description']}")
                if "data" in f and f["data"]:
                    lines.append("")
                    for k, v in f["data"].items():
                        lines.append(f"- **{k}:** {v}")
                lines.append("")

        lines.append("---")
        lines.append(f"*Generated by DiscoveryEngine from {len(self.sessions)} sessions*")
        lines.append("")

        path.write_text("\n".join(lines))
        return path

    # ── pattern finders ─────────────────────────────────────────────────

    def _find_popular_params(self) -> None:
        """Find most popular constraint parameters and ranges."""
        param_counter: Counter[str] = Counter()
        param_values: dict[str, list[Any]] = defaultdict(list)

        for s in self.sessions:
            for action in s.get("actions", []):
                if action.get("event_type") == "param_change":
                    for k, v in action.get("params", {}).items():
                        param_counter[k] += 1
                        if isinstance(v, (int, float)):
                            param_values[k].append(v)

            for comp in s.get("compositions", []):
                for k, v in comp.get("params", {}).items():
                    param_counter[k] += 1
                    if isinstance(v, (int, float)):
                        param_values[k].append(v)

        for param, count in param_counter.most_common(10):
            data: dict[str, Any] = {"usage_count": count}
            if param in param_values and param_values[param]:
                vals = param_values[param]
                data["min"] = round(min(vals), 3)
                data["max"] = round(max(vals), 3)
                data["mean"] = round(sum(vals) / len(vals), 3)

            self._patterns.append({
                "category": "popular_parameters",
                "title": f"Parameter: {param}",
                "description": f"`{param}` was used {count} times across {len(self.sessions)} sessions.",
                "data": data,
            })

    def _find_abandon_points(self) -> None:
        """Find where users tend to abandon sessions."""
        abandon_counter: Counter[str] = Counter()
        total_sessions = len(self.sessions)
        sessions_with_abandon = 0

        for s in self.sessions:
            ap = s.get("abandon_point")
            if ap:
                abandon_counter[ap] += 1
                sessions_with_abandon += 1

        if not abandon_counter:
            self._patterns.append({
                "category": "abandon_points",
                "title": "No abandon points detected",
                "description": "All sessions ended normally.",
                "data": {},
            })
            return

        for point, count in abandon_counter.most_common():
            pct = round(count / total_sessions * 100, 1)
            self._patterns.append({
                "category": "abandon_points",
                "title": f"Abandon point: {point}",
                "description": f"{count} users ({pct}%) abandoned at '{point}'.",
                "data": {"count": count, "percentage": f"{pct}%"},
            })

    def _find_composition_correlations(self) -> None:
        """Find correlations between parameters and session outcomes."""
        # Users who compose more vs. less
        comp_counts = []
        for s in self.sessions:
            comp_counts.append(len(s.get("compositions", [])))

        if not comp_counts:
            return

        avg_comps = sum(comp_counts) / len(comp_counts)
        high_composers = sum(1 for c in comp_counts if c > avg_comps)

        self._patterns.append({
            "category": "composition_patterns",
            "title": "Composition volume distribution",
            "description": f"Average {avg_comps:.1f} compositions per session. "
                           f"{high_composers} users ({round(high_composers/len(comp_counts)*100,1)}%) are 'high composers'.",
            "data": {
                "mean": round(avg_comps, 2),
                "max": max(comp_counts),
                "min": min(comp_counts),
                "high_composers": high_composers,
            },
        })

        # Check if certain parameters correlate with more compositions
        param_comp_count: dict[str, dict[str, list[int]]] = defaultdict(lambda: defaultdict(list))
        for s in self.sessions:
            n_comps = len(s.get("compositions", []))
            seen_params: set[str] = set()
            for action in s.get("actions", []):
                if action.get("event_type") == "param_change":
                    for k, v in action.get("params", {}).items():
                        key = f"{k}={v}"
                        if key not in seen_params:
                            param_comp_count[k][key].append(n_comps)
                            seen_params.add(key)

        for param_key, value_map in param_comp_count.items():
            if len(value_map) < 2:
                continue
            best_val = max(value_map.keys(), key=lambda vk: sum(value_map[vk]) / len(value_map[vk]))
            worst_val = min(value_map.keys(), key=lambda vk: sum(value_map[vk]) / len(value_map[vk]))
            best_avg = sum(value_map[best_val]) / len(value_map[best_val])
            worst_avg = sum(value_map[worst_val]) / len(value_map[worst_val])
            if best_avg > worst_avg * 1.5:
                self._patterns.append({
                    "category": "composition_patterns",
                    "title": f"Parameter impact: {param_key}",
                    "description": f"Users choosing `{best_val}` averaged {best_avg:.1f} compositions vs "
                                   f"`{worst_val}` at {worst_avg:.1f} — "
                                   f"{round(best_avg/worst_avg, 1)}x difference.",
                    "data": {"best": best_val, "worst": worst_val, "ratio": round(best_avg / worst_avg, 2)},
                })

    def _find_session_duration_patterns(self) -> None:
        """Analyze session duration patterns."""
        durations = [s.get("total_duration_s", 0) for s in self.sessions if s.get("total_duration_s")]
        if not durations:
            return

        avg = sum(durations) / len(durations)
        short = sum(1 for d in durations if d < avg * 0.5)
        long = sum(1 for d in durations if d > avg * 1.5)

        self._patterns.append({
            "category": "session_durations",
            "title": "Session length distribution",
            "description": f"Average session: {avg:.1f}s. {short} short sessions (< 50% avg), {long} long sessions (> 150% avg).",
            "data": {
                "mean_seconds": round(avg, 1),
                "median_seconds": round(sorted(durations)[len(durations) // 2], 1),
                "short_sessions": short,
                "long_sessions": long,
            },
        })

    def _find_constraint_combos(self) -> None:
        """Find popular and surprising constraint combinations."""
        combo_counter: Counter[str] = Counter()

        for s in self.sessions:
            constraints: list[str] = []
            for action in s.get("actions", []):
                if action.get("event_type") == "param_change":
                    for k in action.get("params", {}):
                        constraints.append(k)
            for comp in s.get("compositions", []):
                if "constraints" in comp.get("params", {}):
                    for c in comp["params"]["constraints"]:
                        constraints.append(str(c))

            if len(constraints) >= 2:
                # Sort to normalize ordering
                pair = tuple(sorted(set(constraints[:2])))
                combo_counter["+".join(pair)] += 1

        for combo, count in combo_counter.most_common(5):
            self._patterns.append({
                "category": "constraint_combos",
                "title": f"Combo: {combo}",
                "description": f"`{combo}` appeared together in {count} sessions.",
                "data": {"count": count},
            })

    def _find_retention_patterns(self) -> None:
        """Find patterns in user return behavior."""
        user_sessions: dict[str, int] = Counter()
        for s in self.sessions:
            uid = s.get("user_id", "anon")
            user_sessions[uid] += 1

        returning = sum(1 for c in user_sessions.values() if c > 1)
        total_users = len(user_sessions)

        if total_users == 0:
            return

        self._patterns.append({
            "category": "retention",
            "title": "Return rate",
            "description": f"{returning}/{total_users} users ({round(returning/total_users*100,1)}%) "
                           f"returned for multiple sessions.",
            "data": {
                "total_users": total_users,
                "returning_users": returning,
                "max_sessions_per_user": max(user_sessions.values()) if user_sessions else 0,
            },
        })
